services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000

#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: unless-stopped
